package com.erictoader.domain.translator

const val TRANSLATION_WATCHLIST = "TRANSLATION_WATCHLIST"
const val TRANSLATION_CONTINUE_WATCHING = "TRANSLATION_CONTINUE_WATCHING"
const val TRANSLATION_NOW_PLAYING = "TRANSLATION_NOW_PLAYING"
const val TRANSLATION_ON_THE_AIR = "TRANSLATION_ON_THE_AIR"
const val TRANSLATION_AIRING_TODAY = "TRANSLATION_AIRING_TODAY"
const val TRANSLATION_POPULAR = "TRANSLATION_POPULAR"
const val TRANSLATION_UPCOMING = "TRANSLATION_UPCOMING"
const val TRANSLATION_LATEST = "TRANSLATION_LATEST"
const val TRANSLATION_TOP_RATED = "TRANSLATION_TOP_RATED"
const val TRANSLATION_MODULE_CAST = "TRANSLATION_MODULE_CAST"
const val TRANSLATION_MODULE_REVIEWS = "TRANSLATION_MODULE_REVIEWS"
const val TRANSLATION_RECOMMENDED = "TRANSLATION_RECOMMENDED"

interface Translator {

    fun fetchTranslation(keyword: String): String
}
