spring:
  datasource:
    username: movietracker_admin
    password: movietracker_admin
    url: jdbc:mysql://localhost:3306/MovieTracker
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
